#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Hermes reads its configuration from here, not from the project directory.
ENV_FILE="$HOME/.hermes/.env"
MANIFEST="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/slack-app-manifest.yaml"

banner "Connect Slack to Care Operations"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the app from our manifest"
say "The manifest sets the name, the bot user and exactly four permissions."
say "Nothing else is requested, so there is no broad access to approve."
if [[ -f "$MANIFEST" ]]; then
  note "manifest: $MANIFEST"
  # Put it on the clipboard where we can, so there is nothing to retype.
  if command -v clip.exe >/dev/null 2>&1; then
    clip.exe < "$MANIFEST" && printf '  %s✓%s manifest copied to your clipboard\n' "$GREEN" "$RESET"
  elif command -v xclip >/dev/null 2>&1; then
    xclip -selection clipboard < "$MANIFEST" && printf '  %s✓%s manifest copied to your clipboard\n' "$GREEN" "$RESET"
  else
    warn "no clipboard tool; open the file above and copy it by hand"
  fi
else
  warn "manifest not found at $MANIFEST - copy it from setup/ in the repo"
fi
open_url "https://api.slack.com/apps"
step "Click 'Create New App', then choose 'From a manifest'."
step "Pick the 'trt' workspace, then click Next."
step "Delete the sample YAML, paste the manifest (already on your clipboard), Next."
step "Review the four scopes, then click 'Create'."
pause "Done? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Install it into the trt workspace"
say "This is where Slack actually issues the token."
step "In the left sidebar open 'OAuth & Permissions'."
step "Click 'Install to Workspace' at the top of that page."
step "Slack shows what the app can do. Click 'Allow'."
pause "Installed? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Copy the bot token"
say "This token is a password for your workspace. It is typed hidden here and"
say "written straight to the config file - it never appears on screen or in chat."
step "Still on 'OAuth & Permissions', find 'Bot User OAuth Token'."
step "It starts with xoxb-. Click Copy."
ask_secret SLACK_BOT_TOKEN "Paste the bot token:"
if [[ -z "${SLACK_BOT_TOKEN:-}" ]]; then
  warn "no token entered - re-run when you have it"
  exit 1
fi
if [[ "$SLACK_BOT_TOKEN" != xoxb-* ]]; then
  warn "that does not start with xoxb-."
  note "xoxp- is a user token and xapp- is an app-level token; we need the bot one."
  confirm "Save it anyway?" || exit 1
fi
write_env SLACK_BOT_TOKEN "$SLACK_BOT_TOKEN"
# The file now holds a workspace token alongside the mailbox password and the
# model keys. Make sure it is not world-readable.
if [[ -f "$ENV_FILE" ]]; then
  chmod 600 "$ENV_FILE" 2>/dev/null     && printf '  %s✓%s locked %s to your user only (600)
' "$GREEN" "$RESET" "$ENV_FILE"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Invite the bot to the channels it should read"
say "The app can only see channels it has been invited to. That is deliberate:"
say "it reads nothing by default, and you choose what it sees."
open_url "https://app.slack.com/client"
step "Open (or create) the channel your team raises requests in."
step "Type:  /invite @Care Ops   and send it."
step "Repeat for any other channel it should watch."
note "It cannot read private channels or DMs with these permissions."
pause "Invited? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Choose where overdue work gets escalated"
say "When a deadline passes, the daily sweep posts there. Right now it has"
say "nowhere to post, so those alerts are only written to a local log file."
step "Pick a channel for that - a quiet one is better, e.g. #care-ops-alerts."
step "Make sure the bot is invited to it too."
ask SLACK_ESCALATION_CHANNEL "Channel name (with the #):" "#care-ops-alerts"
write_env HERMES_TRT_ESCALATION_TARGET "$SLACK_ESCALATION_CHANNEL"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify the connection"
say "Asking Slack who we are, and which channels the bot can actually see."
if ! command -v curl >/dev/null 2>&1; then
  warn "curl not available - skipping the live check"
  SKIPPED+=("verify the Slack token by hand")
else
  auth=$(curl -sS --max-time 20 -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
           https://slack.com/api/auth.test 2>/dev/null || echo '{"ok":false}')
  if printf '%s' "$auth" | grep -q '"ok":true'; then
    team=$(printf '%s' "$auth" | sed -E 's/.*"team":"([^"]*)".*/\1/')
    user=$(printf '%s' "$auth" | sed -E 's/.*"user":"([^"]*)".*/\1/')
    printf '  %s✓ connected%s as %s in workspace %s\n' "$GREEN" "$RESET" "$user" "$team"

    convo=$(curl -sS --max-time 20 -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
             "https://slack.com/api/users.conversations?types=public_channel&limit=50" \
             2>/dev/null || echo '{"ok":false}')
    if printf '%s' "$convo" | grep -q '"ok":true'; then
      names=$(printf '%s' "$convo" | grep -oE '"name":"[^"]+"' | sed 's/"name":"//;s/"//' | tr '\n' ' ')
      if [[ -n "${names// /}" ]]; then
        printf '  %s✓ can read%s #%s\n' "$GREEN" "$RESET" "${names// / #}"
      else
        warn "the token works, but the bot is not in any channel yet"
        note "go back to Slack and run /invite @Care Ops in the channel you want watched"
        SKIPPED+=("invite the bot to at least one channel")
      fi
    else
      err=$(printf '%s' "$convo" | sed -E 's/.*"error":"([^"]*)".*/\1/')
      warn "could not list channels: $err"
      SKIPPED+=("check the channels:read scope was granted")
    fi
  else
    err=$(printf '%s' "$auth" | sed -E 's/.*"error":"([^"]*)".*/\1/')
    warn "Slack rejected the token: $err"
    note "invalid_auth usually means it was copied short, or it is not the xoxb- one."
    SKIPPED+=("re-run this wizard with a valid bot token")
  fi
fi

finish
note "Next: the message poller is built against this connection."
note "Nothing reads Slack yet - this stage only proves the credentials work."
