#!/usr/bin/env bash
# Register the inbound-message hook with Hermes.
#
# pre_gateway_dispatch fires for every incoming platform message before the
# agent is dispatched. Our hook triages it and returns {"action": "skip"},
# so Hermes never composes a reply to a client. See hooks/inbound_message.py.
#
# fail_closed is deliberate: if the hook cannot run, the message must not
# fall through to an unsupervised agent.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$HOME/.hermes/config.yaml"
SCRIPTS="$HOME/.hermes/scripts"
RUNNER="$SCRIPTS/trt_inbound_hook.sh"

mkdir -p "$SCRIPTS"

echo "==> writing runner"
cat > "$RUNNER" <<RUNNEREOF
#!/bin/sh
# Generated by setup/install-hook.sh. Hermes owns the trigger; the repo owns
# the logic, so editing the hook needs no re-registration.
exec "$REPO/.venv/bin/python" "$REPO/hooks/inbound_message.py"
RUNNEREOF
chmod +x "$RUNNER"
echo "    $RUNNER"

echo "==> registering hook in config.yaml"
python3 - "$CONFIG" "$RUNNER" <<'PYEOF'
import re, shutil, sys
from datetime import datetime

config_path, runner = sys.argv[1:3]
shutil.copy2(config_path, f"{config_path}.{datetime.now():%Y%m%d-%H%M%S}.bak")
text = open(config_path, encoding="utf-8").read()

block = f"""hooks:
  # Triage inbound client messages instead of letting the agent reply.
  # The hook returns {{"action": "skip"}} so Hermes never composes a reply
  # to a client - a safety control, not an optimisation.
  # fail_closed: a hook that cannot run must not let the message through.
  pre_gateway_dispatch:
    - command: "{runner}"
      timeout: 180
      fail_closed: true

hooks_auto_accept: true
"""

if re.search(r"^hooks:", text, re.MULTILINE):
    print("  a hooks: block already exists - leaving it alone")
    print("  review it by hand before changing")
else:
    text = text.rstrip("\n") + "\n\n" + block
    open(config_path, "w", encoding="utf-8").write(text)
    print("  added")
PYEOF

echo
echo "==> verifying"
"$HOME/.local/bin/hermes" hooks list 2>&1 | head -15
