#!/usr/bin/env bash
# Run the mailbox poller on a schedule, so email ingestion does not depend
# on anyone leaving a terminal open.
#
# Uses Hermes' own cron (the gateway must be running), with --no-agent: the
# poller is plain Python and needs no model to decide when to run.
set -uo pipefail
HERMES="$HOME/.local/bin/hermes"
SCRIPTS="$HOME/.hermes/scripts"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$SCRIPTS"
cat > "$SCRIPTS/trt_mailpoll.sh" <<RUNNER
#!/bin/sh
# Generated by setup/install-mailpoll-cron.sh
cd "$REPO" || exit 1
PYTHONPATH="$REPO/src" exec "$REPO/.venv/bin/python" -m hermes_trt.mailpoll
RUNNER
chmod +x "$SCRIPTS/trt_mailpoll.sh"

echo "==> registering mailbox poll (every 2 minutes)"
"$HERMES" cron delete "trt-mailpoll" >/dev/null 2>&1 || true
"$HERMES" cron create "2m" --name "trt-mailpoll" --no-agent \
    --script "trt_mailpoll.sh" 2>&1 | head -8

echo
"$HERMES" cron list 2>&1 | grep -E "Name:|Schedule:|Next run:"
