#!/usr/bin/env bash
# Run the Slack poller on a schedule, the same way the mailbox is polled.
#
# Every 3 minutes rather than 2: chat is less time-critical than a client
# email, and the classifier call is the expensive part of each pass. Staggering
# the two also keeps them off the same model quota window.
set -uo pipefail
HERMES="$HOME/.local/bin/hermes"
SCRIPTS="$HOME/.hermes/scripts"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$SCRIPTS"
cat > "$SCRIPTS/trt_slackpoll.sh" <<RUNNER
#!/bin/sh
# Generated by setup/install-slackpoll-cron.sh
cd "$REPO" || exit 1
PYTHONPATH="$REPO/src" exec "$REPO/.venv/bin/python" -m hermes_trt.slackpoll
RUNNER
chmod +x "$SCRIPTS/trt_slackpoll.sh"

echo "==> registering Slack poll (every 3 minutes)"
"$HERMES" cron delete "trt-slackpoll" >/dev/null 2>&1 || true
"$HERMES" cron create "3m" --name "trt-slackpoll" --no-agent \
    --script "trt_slackpoll.sh" 2>&1 | head -8

echo
"$HERMES" cron list 2>&1 | grep -E "Name:|Schedule:|Next run:"
