#!/usr/bin/env bash
# Register the operational cron jobs with Hermes.
#
# Constraints (see docs/DEPLOYMENT-NOTES.md #7):
#   - Cron scripts must live in ~/.hermes/scripts/ and be referenced by
#     FILENAME ONLY. Absolute paths are rejected.
#   - Jobs only fire while the gateway is running.
#
# The SLA sweep runs with --no-agent: it is date arithmetic, not a task for
# the model. A deadline check that can hallucinate is worse than none.
set -uo pipefail

HERMES="$HOME/.local/bin/hermes"
SCRIPTS="$HOME/.hermes/scripts"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$SCRIPTS"

echo "==> writing runner into $SCRIPTS"
# A thin shim: Hermes owns the schedule, the repo owns the logic. Editing
# the checker does not require re-registering the job.
cat > "$SCRIPTS/trt_sla_check.sh" <<RUNNER
#!/bin/sh
# Daily SLA sweep for TRT Australia. Generated by setup/install-cron-jobs.sh.
exec "$REPO/.venv/bin/python" "$REPO/src/hermes_trt/sla_check.py"
RUNNER
chmod +x "$SCRIPTS/trt_sla_check.sh"
echo "    trt_sla_check.sh"

echo
echo "==> registering daily SLA sweep (09:00)"
"$HERMES" cron delete "trt-sla-check" >/dev/null 2>&1 || true
"$HERMES" cron create "0 9 * * *" \
    --name "trt-sla-check" \
    --no-agent \
    --script "trt_sla_check.sh" 2>&1 | head -10

echo
echo "==> registered jobs"
"$HERMES" cron list 2>&1 | head -20

echo
echo "==> gateway (jobs only fire while this is running)"
"$HERMES" gateway status 2>&1 | head -4
